apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/j5hjun/ai.git
    targetRevision: main
    path: ai/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
